---
apiVersion: v1
kind: Service
metadata:
  name: hellogo
  namespace: hellogo
  labels:
    app: hellogo-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: hellogo-app